name: Template Python CI

on: push

jobs:
  build:
    name: Template Python Code CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3
      - name: Install dependencies
        run: make init_ci
      - name: Make test
        run: make test_ci
      - name: Make lint
        run: make lint_ci
      - name: Make ci
        run: make ci

      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_PYTHON_BLACK: true
          LINTER_RULES_PATH: /
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
